### ISSUE TITLE
Prediction in README using the weights/dataset provided errors

### ISSUE THREAD

**Issue by bgriffen** [ualsg/Roofpedia#3]
Downloading the weights and test dataset (NY) and running `python predict_and_extract.py NY Solar` yields the following error right near the end:

```bash
Eval: 100%|####################################################################################################| 3102/3102 [01:57<00:00, 26.38batch/s]
Prediction Done, saved masks to results\03Masks\Solar\NY
Converting Prediction Masks to GeoJson Features
 76%|###############################################################################3                         | 2344/3102 [00:01<00:00, 1596.60mask/s]Warning: extracted feature is not valid, skipping
100%|#########################################################################################################| 3102/3102 [00:02<00:00, 1535.02mask/s]
C:\Users\bigbang\anaconda3\envs\roofpedia\lib\site-packages\pyproj\crs\crs.py:53: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  return _prepare_from_string(" ".join(pjargs))
Traceback (most recent call last):
  File "predict_and_extract.py", line 38, in <module>
    intersection(target_type, city_name, mask_dir)
  File "E:\ResilioData\Datasets\geospatial\Roofpedia\src\extract.py", line 37, in intersection
    city['area'] = city['geometry'].to_crs({'init': 'epsg:3395'}).map(lambda p: p.area)
  File "C:\Users\bigbang\anaconda3\envs\roofpedia\lib\site-packages\geopandas\geoseries.py", line 1124, in to_crs
    self.values.to_crs(crs=crs, epsg=epsg), index=self.index, name=self.name
  File "C:\Users\bigbang\anaconda3\envs\roofpedia\lib\site-packages\geopandas\array.py", line 779, in to_crs
    new_data = vectorized.transform(self.data, transformer.transform)
  File "C:\Users\bigbang\anaconda3\envs\roofpedia\lib\site-packages\geopandas\_vectorized.py", line 1114, in transform
    new_coords_z = func(coords_z[:, 0], coords_z[:, 1], coords_z[:, 2])
  File "C:\Users\bigbang\anaconda3\envs\roofpedia\lib\site-packages\pyproj\transformer.py", line 430, in transform
    self._transformer._transform(
  File "pyproj/_transformer.pyx", line 459, in pyproj._transformer._Transformer._transform
pyproj.exceptions.ProjError: x, y, z, and time must be same size
```

Which comes from this function in `extract.py`

```python
def intersection(target_type, city_name, mask_dir):
    # predicted features
    print()
    print("Converting Prediction Masks to GeoJson Features")
    features = mask_to_feature(mask_dir)
    prediction = gp.GeoDataFrame.from_features(features, crs=4326) 

    # loading building polygons
    city = 'results/01City/' + city_name + '.geojson'
    city = gp.GeoDataFrame.from_file(city)[['geometry']]  
    city['area'] = city['geometry'].to_crs({'init': 'epsg:3395'}).map(lambda p: p.area)
    
    intersections= gp.sjoin(city, prediction, how="inner", op='intersects')
    intersections = intersections.drop_duplicates(subset=['geometry'])
    intersections.to_file('results/04Results/' + city_name + '_' + target_type + ".geojson", driver='GeoJSON')
    
    print()
    print("Process complete, footprints with " + target_type + " roofs are saved at results/04Results/" + city_name + '_' + target_type + ".geojson")
    return intersections
```

My `conda list` is as follows:

```bash
(roofpedia) >conda list
# packages in environment at C:\Users\bigbang\anaconda3\envs\roofpedia:
#
# Name                    Version                   Build  Channel
appdirs                   1.4.4              pyhd3eb1b0_0
asttokens                 2.0.5              pyhd3eb1b0_0
attrs                     22.1.0           py38haa95532_0
backcall                  0.2.0              pyhd3eb1b0_0
blas                      1.0                         mkl
blosc                     1.21.3               h6c2663c_0
boost-cpp                 1.73.0              h2bbff1b_12
bottleneck                1.3.5            py38h080aedc_0
branca                    0.6.0            py38haa95532_0
brotli                    1.0.9                h2bbff1b_7
brotli-bin                1.0.9                h2bbff1b_7
brotlipy                  0.7.0           py38h2bbff1b_1003
bzip2                     1.0.8                he774522_0
ca-certificates           2023.05.30           haa95532_0
cairo                     1.16.0               haedb8bc_5
certifi                   2023.7.22        py38haa95532_0
cffi                      1.15.1           py38h2bbff1b_3
cfitsio                   3.470                h2bbff1b_7
charset-normalizer        2.0.4              pyhd3eb1b0_0
click                     8.0.4            py38haa95532_0
click-plugins             1.1.1              pyhd3eb1b0_0
cligj                     0.7.2            py38haa95532_0
colorama                  0.4.6            py38haa95532_0
contourpy                 1.0.5            py38h59b6b97_0
cryptography              41.0.2           py38h31511bf_0
cuda-cccl                 12.2.128                      0    nvidia
cuda-cudart               11.7.99                       0    nvidia
cuda-cudart-dev           11.7.99                       0    nvidia
cuda-cupti                11.7.101                      0    nvidia
cuda-libraries            11.7.1                        0    nvidia
cuda-libraries-dev        11.7.1                        0    nvidia
cuda-nvrtc                11.7.99                       0    nvidia
cuda-nvrtc-dev            11.7.99                       0    nvidia
cuda-nvtx                 11.7.91                       0    nvidia
cuda-runtime              11.7.1                        0    nvidia
cudatoolkit               10.2.89              h74a9793_1
curl                      8.1.1                h2bbff1b_1
cycler                    0.11.0             pyhd3eb1b0_0
decorator                 5.1.1              pyhd3eb1b0_0
executing                 0.8.3              pyhd3eb1b0_0
expat                     2.4.9                h6c2663c_0
filelock                  3.9.0            py38haa95532_0
fiona                     1.9.1            py38hf11a4ad_0
folium                    0.14.0           py38haa95532_0
fontconfig                2.14.1               h9c4af85_2
fonttools                 4.25.0             pyhd3eb1b0_0
freetype                  2.12.1               ha860e81_0
freexl                    1.0.6                h2bbff1b_0
gdal                      3.6.2            py38h9eae49a_1
geojson                   3.0.1                    pypi_0    pypi
geopandas                 0.12.2           py38haa95532_0
geopandas-base            0.12.2           py38haa95532_0
geos                      3.8.0                h33f27b4_0
geotiff                   1.7.0                h4545760_1
giflib                    5.2.1                h8cc25b3_3
glib                      2.69.1               h5dc1a3c_2
gst-plugins-base          1.18.5               h9e645db_0
gstreamer                 1.18.5               hd78058f_0
hdf4                      4.2.13               h712560f_2
hdf5                      1.10.6               h1756f20_1
icc_rt                    2022.1.0             h6049295_2
icu                       58.2                 ha925a31_3
idna                      3.4              py38haa95532_0
importlib_resources       5.2.0              pyhd3eb1b0_1
intel-openmp              2023.1.0         h59b6b97_46319
ipython                   8.12.0           py38haa95532_0
jedi                      0.18.1           py38haa95532_1
jinja2                    3.1.2            py38haa95532_0
joblib                    1.2.0            py38haa95532_0
jpeg                      9e                   h2bbff1b_1
kealib                    1.5.0                hde4a422_0
kiwisolver                1.4.4            py38hd77b12b_0
krb5                      1.20.1               h5b6d351_1
lcms2                     2.12                 h83e58a3_0
lerc                      3.0                  hd77b12b_0
libboost                  1.73.0              h6c2663c_12
libbrotlicommon           1.0.9                h2bbff1b_7
libbrotlidec              1.0.9                h2bbff1b_7
libbrotlienc              1.0.9                h2bbff1b_7
libclang                  12.0.0          default_h627e005_2
libcublas                 11.10.3.66                    0    nvidia
libcublas-dev             11.10.3.66                    0    nvidia
libcufft                  10.7.2.124                    0    nvidia
libcufft-dev              10.7.2.124                    0    nvidia
libcurand                 10.3.3.129                    0    nvidia
libcurand-dev             10.3.3.129                    0    nvidia
libcurl                   8.1.1                h86230a5_1
libcusolver               11.4.0.1                      0    nvidia
libcusolver-dev           11.4.0.1                      0    nvidia
libcusparse               11.7.4.91                     0    nvidia
libcusparse-dev           11.7.4.91                     0    nvidia
libdeflate                1.17                 h2bbff1b_0
libffi                    3.4.4                hd77b12b_0
libgdal                   3.6.2                h11d7215_1
libiconv                  1.16                 h2bbff1b_2
libkml                    1.3.0                h63940dd_6
libnetcdf                 4.8.1                h6685c40_2
libnpp                    11.7.4.75                     0    nvidia
libnpp-dev                11.7.4.75                     0    nvidia
libnvjpeg                 11.8.0.2                      0    nvidia
libnvjpeg-dev             11.8.0.2                      0    nvidia
libogg                    1.3.5                h2bbff1b_1
libpng                    1.6.39               h8cc25b3_0
libpq                     12.15                hb652d5d_1
libspatialindex           1.9.3                h6c2663c_0
libspatialite             4.3.0a              h6ec8781_23
libssh2                   1.10.0               hcd4344a_2
libtiff                   4.5.0                h6c2663c_2
libuv                     1.44.2               h2bbff1b_0
libvorbis                 1.3.7                he774522_0
libwebp                   1.2.4                hbc33d0d_1
libwebp-base              1.2.4                h2bbff1b_1
libxml2                   2.10.3               h0ad7f3c_0
libxslt                   1.1.37               h2bbff1b_0
libzip                    1.8.0                h49b8836_0
lz4-c                     1.9.4                h2bbff1b_0
mapclassify               2.5.0            py38haa95532_0
markupsafe                2.1.1            py38h2bbff1b_0
matplotlib                3.7.1            py38haa95532_1
matplotlib-base           3.7.1            py38hf11a4ad_1
matplotlib-inline         0.1.6            py38haa95532_0
mercantile                1.0.4                    pypi_0    pypi
mkl                       2023.1.0         h8bd8f75_46356
mkl-service               2.4.0            py38h2bbff1b_1
mkl_fft                   1.3.6            py38hf11a4ad_1
mkl_random                1.2.2            py38hf11a4ad_1
mpmath                    1.3.0            py38haa95532_0
munch                     2.5.0              pyhd3eb1b0_0
munkres                   1.1.4                      py_0
networkx                  3.1              py38haa95532_0
ninja                     1.10.2               haa95532_5
ninja-base                1.10.2               h6d14046_5
numexpr                   2.8.4            py38h7b80656_1
numpy                     1.24.3           py38h79a8e48_1
numpy-base                1.24.3           py38h8a87ada_1
opencv-python             4.8.0.74                 pypi_0    pypi
openjpeg                  2.4.0                h4fc8c34_0
openssl                   1.1.1u               h2bbff1b_0
packaging                 23.0             py38haa95532_0
pandas                    1.5.3            py38hf11a4ad_0
parso                     0.8.3              pyhd3eb1b0_0
pcre                      8.45                 hd77b12b_0
pcre2                     10.37                h0ff8eda_1
pickleshare               0.7.5           pyhd3eb1b0_1003
pillow                    9.4.0            py38hd77b12b_0
pip                       23.2.1           py38haa95532_0
pixman                    0.40.0               h2bbff1b_1
ply                       3.11                     py38_0
pooch                     1.4.0              pyhd3eb1b0_0
poppler                   22.12.0              h268424c_0
poppler-data              0.4.11               haa95532_1
postgresql                12.15                hb652d5d_1
proj                      6.2.1                h3758d61_0
prompt-toolkit            3.0.36           py38haa95532_0
pure_eval                 0.2.2              pyhd3eb1b0_0
pycparser                 2.21               pyhd3eb1b0_0
pygments                  2.15.1           py38haa95532_1
pyopenssl                 23.2.0           py38haa95532_0
pyparsing                 3.0.9            py38haa95532_0
pyproj                    2.6.1.post1      py38h593ac45_1
pyqt                      5.15.7           py38hd77b12b_0
pyqt5-sip                 12.11.0          py38hd77b12b_0
pysocks                   1.7.1            py38haa95532_0
python                    3.8.17               h6244533_0
python-dateutil           2.8.2              pyhd3eb1b0_0
pytorch                   2.0.1           py3.8_cuda11.7_cudnn8_0    pytorch
pytorch-cuda              11.7                 h16d0643_5    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2022.7           py38haa95532_0
qhull                     2020.2               h59b6b97_2
qt-main                   5.15.2               he8e5bd7_7
qt-webengine              5.15.9               hb9a9bb5_5
qtwebkit                  5.212                h2bbfb41_5
requests                  2.31.0           py38haa95532_0
rtree                     1.0.1            py38h2eaa2aa_0
scikit-learn              1.2.2            py38hd77b12b_1
scipy                     1.10.1           py38hdcfc7df_1
setuptools                68.0.0           py38haa95532_0
shapely                   2.0.1            py38hd7f5953_0
sip                       6.6.2            py38hd77b12b_0
six                       1.16.0             pyhd3eb1b0_1
sqlite                    3.41.2               h2bbff1b_0
stack_data                0.2.0              pyhd3eb1b0_0
sympy                     1.11.1           py38haa95532_0
tbb                       2021.8.0             h59b6b97_0
threadpoolctl             2.2.0              pyh0d69192_0
tiledb                    2.3.3                h3649cd2_2
tk                        8.6.12               h2bbff1b_0
toml                      0.10.2             pyhd3eb1b0_0
torchaudio                2.0.2                    pypi_0    pypi
torchvision               0.15.2                   pypi_0    pypi
tornado                   6.3.2            py38h2bbff1b_0
tqdm                      4.65.0           py38hd4e2768_0
traitlets                 5.7.1            py38haa95532_0
typing-extensions         4.7.1            py38haa95532_0
typing_extensions         4.7.1            py38haa95532_0
urllib3                   1.26.16          py38haa95532_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wcwidth                   0.2.5              pyhd3eb1b0_0
webp                      0.1.6                    pypi_0    pypi
wheel                     0.38.4           py38haa95532_0
win_inet_pton             1.1.0            py38haa95532_0
xerces-c                  3.2.4                hd77b12b_0
xyzservices               2022.9.0         py38haa95532_1
xz                        5.4.2                h8cc25b3_0
zipp                      3.11.0           py38haa95532_0
zlib                      1.2.13               h8cc25b3_0
zstd                      1.5.5                hd43e919_0
```

I've thought I could update it below to check if the geometry `isNotNull` (and updated the `.to_crs` to as `{'init':...` has been deprecated) but this didn't fix it, same error.

```python
def intersection(target_type, city_name, mask_dir):
    # predicted features
    print()
    print("Converting Prediction Masks to GeoJson Features")
    features = mask_to_feature(mask_dir)
    prediction = gp.GeoDataFrame.from_features(features, crs=4326) 

    # loading building polygons
    city = 'results/01City/' + city_name + '.geojson'
    city = gp.GeoDataFrame.from_file(city)[['geometry']]  
    
    # Ensure that all geometries are valid and not null
    city = city.loc[city['geometry'].is_valid & city['geometry'].notnull()]
    
    city['area'] = city['geometry'].to_crs('epsg:3395').map(lambda p: p.area)
    
    intersections= gp.sjoin(city, prediction, how="inner", op='intersects')
    intersections = intersections.drop_duplicates(subset=['geometry'])
    intersections.to_file('results/04Results/' + city_name + '_' + target_type + ".geojson", driver='GeoJSON')
    
    print()
    print("Process complete, footprints with " + target_type + " roofs are saved at results/04Results/" + city_name + '_' + target_type + ".geojson")
    return intersections
```

Any ideas?

**Comment by Petrichor-co** [comment]
I had the same problem, did you solve it please?

**Comment by bgriffen** [comment]
No I hadn't as I left the project after I encountered the above without a solution. Was hoping maybe @fbiljecki might have had an idea.

**Comment by Petrichor-co** [comment]
Thanks! If this demo was working before, I think it might be some package update causing the problem. I hope the author can provide some suggestions and help.

**Comment by Petrichor-co** [comment]
I solved the problem by simply updating the pyproj library to version _3.5.0_ !

**Comment by Iceofsky** [comment]
Hi @Petrichor-co, thanks for providing the solution. Happy building!
